msgfmt -o djangojs-partial.mo djangojs-partial.po
msgfmt -o django-partial.mo django-partial.po
msgfmt -o mako.mo mako.po
msgfmt -o underscore-studio.mo underscore-studio.po
msgfmt -o djangojs.mo djangojs.po
msgfmt -o django.mo django.po
msgfmt -o mako-studio.mo mako-studio.po
msgfmt -o wiki.mo wiki.po
msgfmt -o djangojs-studio.mo djangojs-studio.po
msgfmt -o django-studio.mo django-studio.po
msgfmt -o underscore.mo underscore.po
